spring:
  application:
    name: "serenity-rest-assured-bug-demo"
  main:
    banner-mode: off
    lazy-initialization: false
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
